"""empty message

Revision ID: 23341d8c7c2b
Revises: 82dcf8474666
Create Date: 2024-07-18 17:25:48.661369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23341d8c7c2b'
down_revision = '82dcf8474666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
