"""Update Property model structure

Revision ID: 5f585d5c8398
Revises: 920bf7e62776
Create Date: 2025-04-11 17:21:08.398404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f585d5c8398'
down_revision = '920bf7e62776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('status_result', sa.String(length=50), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('applicant_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('plant_name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('sub_location', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('land_contract', sa.String(length=50), nullable=False),
    sa.Column('observation_point', sa.String(length=50), nullable=True),
    sa.Column('annual_production', sa.Float(), nullable=False),
    sa.Column('power_sale_price', sa.Float(), nullable=False),
    sa.Column('annual_revenue', sa.Float(), nullable=False),
    sa.Column('remaining_revenue', sa.Float(), nullable=False),
    sa.Column('accumulated_revenue', sa.Float(), nullable=False),
    sa.Column('desired_price', sa.Float(), nullable=False),
    sa.Column('land_price', sa.Float(), nullable=False),
    sa.Column('system_price', sa.Float(), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('system_capacity', sa.String(length=50), nullable=True),
    sa.Column('max_output', sa.Float(), nullable=True),
    sa.Column('conversion_efficiency', sa.Float(), nullable=True),
    sa.Column('output_warranty', sa.Integer(), nullable=True),
    sa.Column('product_warranty', sa.Integer(), nullable=True),
    sa.Column('monitoring_system', sa.String(length=10), nullable=True),
    sa.Column('service_cost', sa.Float(), nullable=True),
    sa.Column('inverter_manufacturer', sa.String(length=100), nullable=True),
    sa.Column('max_capacity', sa.Float(), nullable=True),
    sa.Column('inverter_efficiency', sa.Float(), nullable=True),
    sa.Column('inverter_warranty', sa.Integer(), nullable=True),
    sa.Column('inverter_monitoring_system', sa.String(length=10), nullable=True),
    sa.Column('inverter_service_cost', sa.Float(), nullable=True),
    sa.Column('structure_manufacturer', sa.String(length=100), nullable=True),
    sa.Column('construction_method', sa.String(length=50), nullable=True),
    sa.Column('incident_angle', sa.Float(), nullable=True),
    sa.Column('structure_product_warranty', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('included_in_price', sa.String(length=500), nullable=True),
    sa.Column('business_registration_certificate', sa.String(length=200), nullable=True),
    sa.Column('power_business_license', sa.String(length=200), nullable=True),
    sa.Column('grid_connection_contract', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_property_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    # ### end Alembic commands ###
