"""Add fields to Property

Revision ID: 920bf7e62776
Revises: 1fcd8d45f7d4
Create Date: 2025-04-03 14:22:42.882465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920bf7e62776'
down_revision = '1fcd8d45f7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status_result', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('plant_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('completion_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('desired_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_generation', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('business_registration_certificate', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('power_business_license', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('grid_connection_contract', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('grid_connection_contract')
        batch_op.drop_column('power_business_license')
        batch_op.drop_column('business_registration_certificate')
        batch_op.drop_column('notes')
        batch_op.drop_column('average_generation')
        batch_op.drop_column('desired_price')
        batch_op.drop_column('completion_date')
        batch_op.drop_column('address')
        batch_op.drop_column('plant_name')
        batch_op.drop_column('modify_date')
        batch_op.drop_column('status_result')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
